services:
  nginx:
    image: nginx:alpine
    container_name: fortune-ai-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./php-api/public:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl  # SSL 인증서 디렉토리 (선택사항)
    depends_on:
      - php
    restart: unless-stopped
    networks:
      - fortune-ai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  php:
    build: 
      context: ./php-api
      dockerfile: Dockerfile
    container_name: fortune-ai-php
    volumes:
      - ./php-api:/var/www/html
      - ./php-api/.env:/var/www/html/.env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - APP_DEBUG=${APP_DEBUG:-false}
      - TIMEZONE=${TIMEZONE:-Asia/Seoul}
    restart: unless-stopped
    networks:
      - fortune-ai-network
    healthcheck:
      test: ["CMD", "php", "-f", "/var/www/html/public/index.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # PHP-FPM 설정
    command: >
      sh -c "
        php-fpm -D &&
        tail -f /dev/null
      "

networks:
  fortune-ai-network:
    driver: bridge
